version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4173:4173
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
